In [ ]:
import pandas as pd

In [2]:
anime = pd.read_csv(r"data\anime.csv")

In [3]:
anime

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...","Oct 4, 2015 to Mar 27, 2016",25.0,489888,141,25.0,8.82,https://cdn.myanimelist.net/images/anime/9/766...,https://myanimelist.net/anime/28891/Haikyuu_Se...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...","Oct 10, 2014 to Mar 20, 2015",22.0,995473,28,24.0,8.83,https://cdn.myanimelist.net/images/anime/3/671...,https://myanimelist.net/anime/23273/Shigatsu_w...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...","Jul 7, 2017 to Sep 29, 2017",13.0,581663,98,23.0,8.83,https://cdn.myanimelist.net/images/anime/6/867...,https://myanimelist.net/anime/34599/Made_in_Abyss
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']","Jan 6, 2017",1.0,214621,502,22.0,8.83,https://cdn.myanimelist.net/images/anime/3/815...,https://myanimelist.net/anime/31758/Kizumonoga...
...,...,...,...,...,...,...,...,...,...,...,...,...
15381,32979,Flip Flappers,Cocona is an average middle schooler living wi...,"['Sci-Fi', 'Adventure', 'Comedy', 'Magic']","Oct 6, 2016 to Dec 29, 2016",13.0,134252,843,1070.0,7.73,https://cdn.myanimelist.net/images/anime/4/822...,https://myanimelist.net/anime/32979/Flip_Flappers
15382,123,Fushigi Yuugi,"While visiting the National Library, junior-hi...","['Adventure', 'Fantasy', 'Magic', 'Martial Art...","Apr 6, 1995 to Mar 28, 1996",52.0,84407,1292,1071.0,7.73,https://cdn.myanimelist.net/images/anime/2/201...,https://myanimelist.net/anime/123/Fushigi_Yuugi
15383,1281,Gakkou no Kaidan,"Years ago, all of the ghosts in a haunted scho...","['Mystery', 'Horror', 'Supernatural']","Oct 22, 2000 to Mar 25, 2001",19.0,83093,1314,1073.0,7.73,https://cdn.myanimelist.net/images/anime/9/183...,https://myanimelist.net/anime/1281/Gakkou_no_K...
15384,450,InuYasha Movie 2: Kagami no Naka no Mugenjo,Inuyasha and company have finally destroyed Na...,"['Action', 'Adventure', 'Comedy', 'Historical'...","Dec 21, 2002",1.0,71989,1469,1077.0,7.73,https://cdn.myanimelist.net/images/anime/1162/...,https://myanimelist.net/anime/450/InuYasha_Mov...
15385,87,Mobile Suit Gundam: Char's Counterattack,The year is Universal Century 0093. Char Aznab...,"['Military', 'Sci-Fi', 'Space', 'Drama', 'Mecha']","Mar 12, 1988",1.0,29248,2604,1081.0,7.73,https://cdn.myanimelist.net/images/anime/1523/...,https://myanimelist.net/anime/87/Mobile_Suit_G...

In [4]:
anime = anime[["uid","title","synopsis","genre"]]

In [5]:
anime

,uid,title,synopsis,genre
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun..."
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun..."
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F..."
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ..."
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']"
...,...,...,...,...
15381,32979,Flip Flappers,Cocona is an average middle schooler living wi...,"['Sci-Fi', 'Adventure', 'Comedy', 'Magic']"
15382,123,Fushigi Yuugi,"While visiting the National Library, junior-hi...","['Adventure', 'Fantasy', 'Magic', 'Martial Art..."
15383,1281,Gakkou no Kaidan,"Years ago, all of the ghosts in a haunted scho...","['Mystery', 'Horror', 'Supernatural']"
15384,450,InuYasha Movie 2: Kagami no Naka no Mugenjo,Inuyasha and company have finally destroyed Na...,"['Action', 'Adventure', 'Comedy', 'Historical'..."
15385,87,Mobile Suit Gundam: Char's Counterattack,The year is Universal Century 0093. Char Aznab...,"['Military', 'Sci-Fi', 'Space', 'Drama', 'Mecha']"

In [6]:
anime.isnull().sum()

uid         0
title       0
synopsis    0
genre       0
dtype: int64

In [7]:
def remove_space(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [8]:
import ast
anime["genre"] = anime["genre"].apply(ast.literal_eval)

C:\Users\jatin\AppData\Local\Temp\ipykernel_13184\3480558833.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime["genre"] = anime["genre"].apply(ast.literal_eval)

anime['title'] = anime['title'].apply(remove_space)
anime['synopsis'] = anime['synopsis'].apply(remove_space)
anime['genre'] = anime['genre'].apply(remove_space)

In [9]:
anime.head()

,uid,title,synopsis,genre
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"[Comedy, Sports, Drama, School, Shounen]"
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"[Drama, Music, Romance, School, Shounen]"
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"[Sci-Fi, Adventure, Mystery, Drama, Fantasy]"
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","[Action, Military, Adventure, Comedy, Drama, M..."
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"[Action, Mystery, Supernatural, Vampire]"

In [10]:
anime['synopsis'] = anime['synopsis'].apply(lambda x: x.split() if isinstance(x, str) else x)
anime.sample(4)

C:\Users\jatin\AppData\Local\Temp\ipykernel_13184\3280986194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime['synopsis'] = anime['synopsis'].apply(lambda x: x.split() if isinstance(x, str) else x)

,uid,title,synopsis,genre
1239,6062,Duel Masters Movie 2: Lunatic God Saga,"[Five, Enlightened, cards, scatters, all, arou...","[Action, Adventure, Comedy, Shounen]"
5816,2928,.hack//G.U. Returner,"[The, characters, from, previous, .hack//G.U.,...","[Magic, Adventure, Fantasy, Game, Sci-Fi, Drama]"
5349,9526,Wolf Guy,"[Akira, lnugami, is, infected, with, a, terrib...","[Action, Military, Sci-Fi]"
4146,37767,Xingfu Lushang,"[Chi, earned, her, American, dream, after, per...",[Drama]

In [11]:
anime["tags"] = anime["synopsis"] + anime["genre"]

C:\Users\jatin\AppData\Local\Temp\ipykernel_13184\2043965691.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime["tags"] = anime["synopsis"] + anime["genre"]

In [12]:
anime.head()

,uid,title,synopsis,genre,tags
0,28891,Haikyuu!! Second Season,"[Following, their, participation, at, the, Int...","[Comedy, Sports, Drama, School, Shounen]","[Following, their, participation, at, the, Int..."
1,23273,Shigatsu wa Kimi no Uso,"[Music, accompanies, the, path, of, the, human...","[Drama, Music, Romance, School, Shounen]","[Music, accompanies, the, path, of, the, human..."
2,34599,Made in Abyss,"[The, Abyss—a, gaping, chasm, stretching, down...","[Sci-Fi, Adventure, Mystery, Drama, Fantasy]","[The, Abyss—a, gaping, chasm, stretching, down..."
3,5114,Fullmetal Alchemist: Brotherhood,"[""In, order, for, something, to, be, obtained,...","[Action, Military, Adventure, Comedy, Drama, M...","[""In, order, for, something, to, be, obtained,..."
4,31758,Kizumonogatari III: Reiketsu-hen,"[After, helping, revive, the, legendary, vampi...","[Action, Mystery, Supernatural, Vampire]","[After, helping, revive, the, legendary, vampi..."

In [13]:
new_df = anime[['uid','title','tags']]

In [14]:
new_df.head()

,uid,title,tags
0,28891,Haikyuu!! Second Season,"[Following, their, participation, at, the, Int..."
1,23273,Shigatsu wa Kimi no Uso,"[Music, accompanies, the, path, of, the, human..."
2,34599,Made in Abyss,"[The, Abyss—a, gaping, chasm, stretching, down..."
3,5114,Fullmetal Alchemist: Brotherhood,"[""In, order, for, something, to, be, obtained,..."
4,31758,Kizumonogatari III: Reiketsu-hen,"[After, helping, revive, the, legendary, vampi..."

In [15]:
new_df.iloc[0]['tags']

['Following',
 'their',
 'participation',
 'at',
 'the',
 'Inter-High,',
 'the',
 'Karasuno',
 'High',
 'School',
 'volleyball',
 'team',
 'attempts',
 'to',
 'refocus',
 'their',
 'efforts,',
 'aiming',
 'to',
 'conquer',
 'the',
 'Spring',
 'tournament',
 'instead.',
 'When',
 'they',
 'receive',
 'an',
 'invitation',
 'from',
 'long-standing',
 'rival',
 'Nekoma',
 'High,',
 'Karasuno',
 'agrees',
 'to',
 'take',
 'part',
 'in',
 'a',
 'large',
 'training',
 'camp',
 'alongside',
 'many',
 'notable',
 'volleyball',
 'teams',
 'in',
 'Tokyo',
 'and',
 'even',
 'some',
 'national',
 'level',
 'players.',
 'By',
 'playing',
 'with',
 'some',
 'of',
 'the',
 'toughest',
 'teams',
 'in',
 'Japan,',
 'they',
 'hope',
 'not',
 'only',
 'to',
 'sharpen',
 'their',
 'skills,',
 'but',
 'also',
 'come',
 'up',
 'with',
 'new',
 'attacks',
 'that',
 'would',
 'strengthen',
 'them.',
 'Moreover,',
 'Hinata',
 'and',
 'Kageyama',
 'attempt',
 'to',
 'devise',
 'a',
 'more',
 'powerful',
 'weapon,',
 'one',
 'that',
 'could',
 'possibly',
 'break',
 'the',
 'sturdiest',
 'of',
 'blocks.',
 'Facing',
 'what',
 'may',
 'be',
 'their',
 'last',
 'chance',
 'at',
 'victory',
 'before',
 'the',
 'senior',
 'players',
 'graduate,',
 'the',
 'members',
 'of',
 "Karasuno's",
 'volleyball',
 'team',
 'must',
 'learn',
 'to',
 'settle',
 'their',
 'differences',
 'and',
 'train',
 'harder',
 'than',
 'ever',
 'if',
 'they',
 'hope',
 'to',
 'overcome',
 'formidable',
 'opponents',
 'old',
 'and',
 'new—including',
 'their',
 'archrival',
 'Aoba',
 'Jousai',
 'and',
 'its',
 'world-class',
 'setter',
 'Tooru',
 'Oikawa.',
 '[Written',
 'by',
 'MAL',
 'Rewrite]',
 'Comedy',
 'Sports',
 'Drama',
 'School',
 'Shounen']

In [16]:
# Converting list to str
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

C:\Users\jatin\AppData\Local\Temp\ipykernel_13184\3674298559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

,uid,title,tags
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth..."
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...

In [17]:
new_df.iloc[1]['tags']

"Music accompanies the path of the human metronome, the prodigious pianist Kousei Arima. But after the passing of his mother, Saki Arima, Kousei falls into a downward spiral, rendering him unable to hear the sound of his own piano. Two years later, Kousei still avoids the piano, leaving behind his admirers and rivals, and lives a colorless life alongside his friends Tsubaki Sawabe and Ryouta Watari. However, everything changes when he meets a beautiful violinist, Kaori Miyazono, who stirs up his world and sets him on a journey to face music again. Based on the manga series of the same name, Shigatsu wa Kimi no Uso approaches the story of Kousei's recovery as he discovers that music is more than playing each note perfectly, and a single melody can bring in the fresh spring air of April. [Written by MAL Rewrite] Drama Music Romance School Shounen"

In [18]:
anime.iloc[1]['synopsis']

['Music',
 'accompanies',
 'the',
 'path',
 'of',
 'the',
 'human',
 'metronome,',
 'the',
 'prodigious',
 'pianist',
 'Kousei',
 'Arima.',
 'But',
 'after',
 'the',
 'passing',
 'of',
 'his',
 'mother,',
 'Saki',
 'Arima,',
 'Kousei',
 'falls',
 'into',
 'a',
 'downward',
 'spiral,',
 'rendering',
 'him',
 'unable',
 'to',
 'hear',
 'the',
 'sound',
 'of',
 'his',
 'own',
 'piano.',
 'Two',
 'years',
 'later,',
 'Kousei',
 'still',
 'avoids',
 'the',
 'piano,',
 'leaving',
 'behind',
 'his',
 'admirers',
 'and',
 'rivals,',
 'and',
 'lives',
 'a',
 'colorless',
 'life',
 'alongside',
 'his',
 'friends',
 'Tsubaki',
 'Sawabe',
 'and',
 'Ryouta',
 'Watari.',
 'However,',
 'everything',
 'changes',
 'when',
 'he',
 'meets',
 'a',
 'beautiful',
 'violinist,',
 'Kaori',
 'Miyazono,',
 'who',
 'stirs',
 'up',
 'his',
 'world',
 'and',
 'sets',
 'him',
 'on',
 'a',
 'journey',
 'to',
 'face',
 'music',
 'again.',
 'Based',
 'on',
 'the',
 'manga',
 'series',
 'of',
 'the',
 'same',
 'name,',
 'Shigatsu',
 'wa',
 'Kimi',
 'no',
 'Uso',
 'approaches',
 'the',
 'story',
 'of',
 "Kousei's",
 'recovery',
 'as',
 'he',
 'discovers',
 'that',
 'music',
 'is',
 'more',
 'than',
 'playing',
 'each',
 'note',
 'perfectly,',
 'and',
 'a',
 'single',
 'melody',
 'can',
 'bring',
 'in',
 'the',
 'fresh',
 'spring',
 'air',
 'of',
 'April.',
 '[Written',
 'by',
 'MAL',
 'Rewrite]']

In [19]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\jatin\AppData\Local\Temp\ipykernel_13184\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [20]:
new_df.head()

,uid,title,tags
0,28891,Haikyuu!! Second Season,following their participation at the inter-hig...
1,23273,Shigatsu wa Kimi no Uso,music accompanies the path of the human metron...
2,34599,Made in Abyss,the abyss—a gaping chasm stretching down into ...
3,5114,Fullmetal Alchemist: Brotherhood,"""in order for something to be obtained, someth..."
4,31758,Kizumonogatari III: Reiketsu-hen,after helping revive the legendary vampire kis...

In [21]:
import nltk
from nltk.stem import PorterStemmer

In [22]:
ps = PorterStemmer()

In [23]:
def stems(text):
    T = []
    
    for i in text.split():
        T.append(ps.stem(i))
    
    return " ".join(T)

In [24]:
new_df['tags'] = new_df['tags'].apply(stems)

C:\Users\jatin\AppData\Local\Temp\ipykernel_13184\3973021881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stems)

In [25]:
new_df.iloc[0]['tags']

"follow their particip at the inter-high, the karasuno high school volleybal team attempt to refocu their efforts, aim to conquer the spring tournament instead. when they receiv an invit from long-stand rival nekoma high, karasuno agre to take part in a larg train camp alongsid mani notabl volleybal team in tokyo and even some nation level players. by play with some of the toughest team in japan, they hope not onli to sharpen their skills, but also come up with new attack that would strengthen them. moreover, hinata and kageyama attempt to devis a more power weapon, one that could possibl break the sturdiest of blocks. face what may be their last chanc at victori befor the senior player graduate, the member of karasuno' volleybal team must learn to settl their differ and train harder than ever if they hope to overcom formid oppon old and new—includ their archriv aoba jousai and it world-class setter tooru oikawa. [written by mal rewrite] comedi sport drama school shounen"

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [27]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [28]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
vector.shape

(15386, 5000)

In [30]:
len(cv.get_feature_names_out())

5000

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
similarity = cosine_similarity(vector)

In [33]:
similarity

array([[1.        , 0.1024631 , 0.07499531, ..., 0.10397158, 0.06698028,
        0.06727032],
       [0.1024631 , 1.        , 0.12198751, ..., 0.13780177, 0.12451456,
        0.12401163],
       [0.07499531, 0.12198751, 1.        , ..., 0.12103268, 0.0546812 ,
        0.15377035],
       ...,
       [0.10397158, 0.13780177, 0.12103268, ..., 1.        , 0.02807726,
        0.05921758],
       [0.06698028, 0.12451456, 0.0546812 , ..., 0.02807726, 1.        ,
        0.10627216],
       [0.06727032, 0.12401163, 0.15377035, ..., 0.05921758, 0.10627216,
        1.        ]])

In [34]:
new_df[new_df['title'] == 'Made in Abyss'].index[0]

2

In [35]:
def recommend(anime):
    index = new_df[new_df['title'] == anime].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [36]:
recommend('Made in Abyss')

Made in Abyss
Pandora Hearts
Pandora Hearts
Eden's Bowy
Uchuu Kaizoku Captain Herlock

In [37]:
import pickle

In [38]:
pickle.dump(new_df,open('artifacts/anime_list.pkl','wb'))
pickle.dump(similarity,open('artifacts/anime_similarity.pkl','wb'))

In [39]:
recommend('Naruto')

Naruto
Boruto: Naruto the Movie
Naruto: Shippuuden
Naruto: Shippuuden
Boruto: Naruto Next Generations